--- #YAML:1.0
name:                Bit-Vector
version:             6.9
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp::Clan:                    5.3
    Storable:                      2.2
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
